"use server";

import { createClient } from "@/utils/supabase/server";
import {
  AdminCreateBookingSchema,
  AdminBookingInput,
  CompleteBookingType,
} from "@/lib/schemas/booking";
import { revalidatePath } from "next/cache";
import { getInspectionTemplate, getContractTemplate } from "@/actions/settings";

export type ActionState = {
  success?: boolean;
  message: string | null;
  errors?: Record<string, string[]>;
  bookingId?: string;
};

// --- 5. CREATE (Customer Booking Request) ---
export async function createCustomerBooking(data: any): Promise<ActionState> {
  const supabase = await createClient();

  // 1. Authenticate the User
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();
  if (authError || !user) {
    return {
      success: false,
      message: "You must be logged in to book a vehicle.",
    };
  }

  // 2. Call the Atomic RPC
  const { data: bookingId, error } = await supabase.rpc(
    "create_customer_booking_v1",
    {
      p_user_id: user.id,
      p_car_id: data.car_id,
      p_start_date: new Date(data.start_date).toISOString(),
      p_end_date: new Date(data.end_date).toISOString(),
      p_pickup_loc: data.pickup_location,
      p_dropoff_loc: data.dropoff_location,
      p_pickup_type: data.pickup_type,
      p_dropoff_type: data.dropoff_type,
      p_pickup_price: data.pickup_price,
      p_dropoff_price: data.dropoff_price,
      p_is_with_driver: data.is_with_driver,
      p_base_rate_snapshot: data.daily_rate,
      p_total_price: data.grand_total,
      p_security_deposit: data.security_deposit,
      p_pickup_coordinates: data.pickup_coords,
      p_dropoff_coordinates: data.dropoff_coords,
    },
  );

  if (error) {
    console.error("RPC Error (Customer Booking):", error);
    // Return the specific error message generated by our RAISE EXCEPTION in SQL
    return {
      success: false,
      message: error.message || "Failed to submit booking request.",
    };
  }

  // 3. Revalidate the UI
  revalidatePath("/customer/my-bookings");
  revalidatePath("/admin/bookings");

  return { success: true, message: "Booking request submitted successfully!" };
}

// --- 1. CREATE (Admin Super Form) ---
export async function createAdminBooking(data: unknown) {
  const supabase = await createClient();

  // 1. Validate Input
  const result = AdminCreateBookingSchema.safeParse(data);
  if (!result.success) {
    return {
      success: false,
      message: "Validation Failed",
      errors: result.error.flatten().fieldErrors,
    };
  }
  const input = result.data;

  // =========================================================================
  // NEW: CONFLICT CHECK (The "Block and Alert" Method)
  // =========================================================================
  // This looks for any active booking where:
  // Existing Start < New End  AND  Existing End > New Start
  const { data: conflicts, error: conflictError } = await supabase
    .from("bookings")
    .select("booking_id")
    .eq("car_id", input.car_id)
    // We only care about blocking statuses. Pending requests don't block admins.
    .in("booking_status", ["confirmed", "ongoing", "maintenance"])
    .lt("start_date", input.end_date.toISOString())
    .gt("end_date", input.start_date.toISOString())
    .limit(1); // We only need to find 1 to know there's a conflict

  if (conflictError) {
    console.error("Conflict Check Error:", conflictError);
    return {
      success: false,
      message: "Database error while verifying availability.",
    };
  }

  if (conflicts && conflicts.length > 0) {
    return {
      success: false,
      message:
        "Conflict: This vehicle is already booked or under maintenance during the selected dates.",
    };
  }
  // =========================================================================

  // 2. Calculate Base Rent Logic
  const days =
    Math.ceil(
      (input.end_date.getTime() - input.start_date.getTime()) /
        (1000 * 60 * 60 * 24),
    ) || 1;

  let dailyRate = input.custom_daily_rate;
  if (!dailyRate) {
    const { data: car } = await supabase
      .from("cars")
      .select("rental_rate_per_day")
      .eq("car_id", input.car_id)
      .single();
    if (!car) return { success: false, message: "Car not found" };
    dailyRate = car.rental_rate_per_day;
  }
  const baseRent = days * dailyRate!;

  // 3. COMPILE ALL CHARGES
  const charges = [];

  // A. Base Rent
  charges.push({
    category: "Base Rate",
    amount: baseRent,
    description: `${days} days @ ₱${dailyRate}/day`,
  });

  // B. Driver Fee
  if (input.with_driver) {
    const driverTotal = days * input.driver_fee_per_day;
    charges.push({
      category: "Driver Fee",
      amount: driverTotal,
      description: `Chauffeur service (${days} days)`,
    });
  }

  // C. Pickup/Dropoff Fees
  if (input.pickup_price > 0) {
    charges.push({
      category: "Delivery Fee",
      amount: input.pickup_price,
      description: "Pickup: " + input.pickup_location,
    });
  }
  if (input.dropoff_price > 0) {
    charges.push({
      category: "Delivery Fee",
      amount: input.dropoff_price,
      description: "Dropoff: " + input.dropoff_location,
    });
  }

  // D. Additional Charges
  if (input.additional_charges && input.additional_charges.length > 0) {
    input.additional_charges.forEach((c) => {
      charges.push({
        category: c.category,
        amount: c.amount,
        description: c.description || "Extra Item",
      });
    });
  }

  // E. Discount
  if (input.discount_amount > 0) {
    charges.push({
      category: "Discount",
      amount: -input.discount_amount,
      description: "Admin Discount",
    });
  }

  if (input.initial_payment && isNaN(input.initial_payment.amount)) {
    return { success: false, message: "Invalid Payment Amount" };
  }

  const masterTemplate = await getInspectionTemplate();
  let fillableChecklist = null;

  if (masterTemplate && masterTemplate.length > 0) {
    fillableChecklist = masterTemplate.map((category) => ({
      categoryId: category.id,
      categoryName: category.name,
      items: category.items.map((item) => ({
        itemId: item.id,
        label: item.label,
        status: "PENDING", // Pre-fill the staff action states
        notes: "",
        photoUrl: null,
      })),
    }));
  }

  const rawContract = await getContractTemplate();
  let filledContractHtml = null;

  // 2. Fetch the Customer & Car details (if you don't already have them in 'input')
  const { data: customer } = await supabase
    .from("users")
    .select("full_name, address")
    .eq("user_id", input.user_id)
    .single();
  const { data: carData } = await supabase
    .from("cars")
    .select("brand, model, plate_number")
    .eq("car_id", input.car_id)
    .single();

  if (rawContract && customer && carData) {
    // 3. Inject variables into the HTML
    filledContractHtml = rawContract
      .replace(/{{CUSTOMER_NAME}}/g, customer.full_name || "Unknown Customer")
      .replace(
        /{{CUSTOMER_ADDRESS}}/g,
        customer.address || "Address not provided",
      )
      .replace(/{{CAR_BRAND_MODEL}}/g, `${carData.brand} ${carData.model}`)
      .replace(/{{PLATE_NUMBER}}/g, carData.plate_number)
      .replace(/{{START_DATE}}/g, input.start_date.toLocaleDateString())
      .replace(/{{END_DATE}}/g, input.end_date.toLocaleDateString())
      .replace(/{{TOTAL_PRICE}}/g, baseRent.toFixed(2)) // Or total including charges
      .replace(
        /{{SECURITY_DEPOSIT}}/g,
        (input.security_deposit || 0).toFixed(2),
      );
  }

  // 4. Call the RPC
  const { data: bookingId, error } = await supabase.rpc(
    "admin_create_booking_v1",
    {
      p_user_id: input.user_id,
      p_car_id: input.car_id,
      p_start_date: input.start_date.toISOString(),
      p_end_date: input.end_date.toISOString(),
      p_pickup_loc: input.pickup_location,
      p_dropoff_loc: input.dropoff_location,
      p_pickup_coordinates: input.pickup_coordinates || null,
      p_dropoff_coordinates: input.dropoff_coordinates || null,
      p_pickup_type: input.pickup_type,
      p_dropoff_type: input.dropoff_type,
      p_pickup_price: input.pickup_price,
      p_dropoff_price: input.dropoff_price,
      p_is_with_driver: input.with_driver,
      p_base_rate_snapshot: dailyRate,
      p_security_deposit: input.security_deposit,
      p_charges_json: charges,
      p_initial_payment_json: input.initial_payment ?? null,
      p_inspection_template: fillableChecklist,
      p_contract_html: filledContractHtml,
    },
  );

  if (error) {
    console.error("RPC Error:", error);
    return { success: false, message: error.message };
  }

  revalidatePath("/admin/bookings");
  return { success: true, message: "Booking created successfully", bookingId };
}

export async function updateAdminBooking(bookingId: string, data: unknown) {
  const supabase = await createClient();

  // 1. Validate Input
  const result = AdminCreateBookingSchema.safeParse(data);
  if (!result.success) {
    return {
      success: false,
      message: "Validation Failed",
      errors: result.error.flatten().fieldErrors,
    };
  }
  const input = result.data;

  // 2. Calculate Base Rent Logic
  const days =
    Math.ceil(
      (input.end_date.getTime() - input.start_date.getTime()) /
        (1000 * 60 * 60 * 24),
    ) || 1;

  let dailyRate = input.custom_daily_rate;
  if (!dailyRate) {
    const { data: car } = await supabase
      .from("cars")
      .select("rental_rate_per_day")
      .eq("car_id", input.car_id)
      .single();
    if (!car) return { success: false, message: "Car not found" };
    dailyRate = car.rental_rate_per_day;
  }
  const baseRent = days * dailyRate!;

  // 3. COMPILE ALL CHARGES
  const charges = [];

  // A. Base Rent
  charges.push({
    category: "Base Rate",
    amount: baseRent,
    description: `${days} days @ ₱${dailyRate}/day`,
  });

  // B. Driver Fee
  if (input.with_driver) {
    const driverTotal = days * input.driver_fee_per_day;
    charges.push({
      category: "Driver Fee",
      amount: driverTotal,
      description: `Chauffeur service (${days} days)`,
    });
  }

  // C. Pickup/Dropoff Fees
  if (input.pickup_price > 0) {
    charges.push({
      category: "Delivery Fee",
      amount: input.pickup_price,
      description: "Pickup: " + input.pickup_location,
    });
  }
  if (input.dropoff_price > 0) {
    charges.push({
      category: "Delivery Fee",
      amount: input.dropoff_price,
      description: "Dropoff: " + input.dropoff_location,
    });
  }

  // D. Additional Charges
  if (input.additional_charges && input.additional_charges.length > 0) {
    input.additional_charges.forEach((c) => {
      charges.push({
        category: c.category,
        amount: c.amount,
        description: c.description || "Extra Item",
      });
    });
  }

  // E. Discount
  if (input.discount_amount > 0) {
    charges.push({
      category: "Discount",
      amount: -input.discount_amount,
      description: "Admin Discount",
    });
  }

  if (input.initial_payment && isNaN(input.initial_payment.amount)) {
    return { success: false, message: "Invalid Payment Amount" };
  }

  // 4. Call the Update RPC
  const { error } = await supabase.rpc("admin_update_booking_v1", {
    p_booking_id: bookingId, // <--- THIS IS THE ONLY DIFFERENCE
    p_user_id: input.user_id,
    p_car_id: input.car_id,
    p_start_date: input.start_date.toISOString(),
    p_end_date: input.end_date.toISOString(),
    p_pickup_loc: input.pickup_location,
    p_dropoff_loc: input.dropoff_location,
    p_pickup_coordinates: input.pickup_coordinates || null,
    p_dropoff_coordinates: input.dropoff_coordinates || null,
    p_pickup_type: input.pickup_type,
    p_dropoff_type: input.dropoff_type,
    p_pickup_price: input.pickup_price,
    p_dropoff_price: input.dropoff_price,
    p_is_with_driver: input.with_driver,
    p_base_rate_snapshot: dailyRate,
    p_security_deposit: input.security_deposit,
    p_charges_json: charges,
    p_new_payment_json: input.initial_payment ?? null, // Note: named differently in update RPC
  });

  if (error) {
    console.error("RPC Error:", error);
    return { success: false, message: error.message };
  }

  revalidatePath("/admin/bookings");
  return { success: true, message: "Booking updated successfully" };
}

// --- 2. READ (Single Booking) ---
export async function getBookingById(
  id: string,
): Promise<CompleteBookingType | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("bookings")
    .select(
      `
      *,
      user: users(full_name, email, phone_number, profile_picture_url),
      car: cars(brand, model, plate_number, car_images(image_url, is_primary))
    `,
    )
    .eq("booking_id", id)
    .single();

  if (error) return null;

  const booking = data as any;
  if (booking.car && booking.car.car_images) {
    const primary = booking.car.car_images.find((img: any) => img.is_primary);
    booking.car.image_url = primary
      ? primary.image_url
      : booking.car.car_images[0]?.image_url;
  }

  return booking as CompleteBookingType;
}

// --- 3. UPDATE STATUS ---
export async function updateBookingStatus(
  bookingId: string,
  newStatus: string,
): Promise<ActionState> {
  const supabase = await createClient();

  const { error } = await supabase
    .from("bookings")
    .update({
      booking_status: newStatus,
      last_updated_at: new Date().toISOString(),
    })
    .eq("booking_id", bookingId);

  if (error) return { success: false, message: error.message };

  revalidatePath("/admin/bookings");
  revalidatePath(`/admin/bookings/${bookingId}`);
  return { success: true, message: "Status updated" };
}

// --- 4. DELETE ---
export async function deleteBooking(id: string): Promise<ActionState> {
  const supabase = await createClient();

  const { error } = await supabase
    .from("bookings")
    .update({ is_archived: true })
    .eq("booking_id", id);

  if (error) return { success: false, message: error.message };

  revalidatePath("/admin/bookings");
  return { success: true, message: "Booking archived" };
}

// udpate booking dates
export async function updateBookingDates(
  bookingId: string,
  newEndDate: Date,
): Promise<ActionState> {
  const supabase = await createClient();

  const { error } = await supabase
    .from("bookings")
    .update({
      end_date: newEndDate.toISOString(),
      last_updated_at: new Date().toISOString(),
    })
    .eq("booking_id", bookingId);

  if (error) {
    console.error("Error updating booking dates:", error);
    return { success: false, message: error.message };
  }

  revalidatePath("/admin/bookings");
  return { success: true, message: "Booking dates updated" };
}

// update buffer duration
export async function updateBufferDuration(
  bookingId: string,
  newBufferMinutes: number,
): Promise<ActionState> {
  const supabase = await createClient();

  const { error } = await supabase
    .from("bookings")
    .update({
      buffer_duration: newBufferMinutes,
      last_updated_at: new Date().toISOString(),
    })
    .eq("booking_id", bookingId);

  if (error) {
    console.error("Error updating buffer duration:", error);
    return { success: false, message: error.message };
  }

  revalidatePath("/admin/bookings");
  return { success: true, message: "Buffer duration updated" };
}

export async function processEarlyReturn(
  bookindId: string,
  newEndDate: Date,
  finalPrice: number,
  refundAmount: number,
  shouldRefund: boolean,
): Promise<ActionState> {
  const supabase = await createClient();

  try {
    const { error } = await supabase.rpc("process_early_return", {
      p_booking_id: bookindId,
      p_new_end_date: newEndDate,
      p_final_price: finalPrice,
      p_refund_amount: refundAmount,
      p_should_refund: shouldRefund,
    });

    if (error) throw error;
    return { success: true, message: "Early return processed successfully" };
  } catch (error) {
    console.error("Failed to process early return via RPC:", error);
    return { success: false, message: "Failed to process early return" };
  }
}

export async function createMaintenanceBlock(
  carId: string,
  startDate: Date,
  endDate: Date,
): Promise<ActionState> {
  const supabase = await createClient();

  try {
    const { data, error } = await supabase
      .from("bookings")
      .insert({
        car_id: carId,
        start_date: startDate.toISOString(),
        end_date: endDate.toISOString(),
        booking_status: "maintenance",
        total_price: 0,
      })
      .select("booking_id")
      .single();

    if (error) throw error;
    revalidatePath("/admin/bookings");
    return {
      success: true,
      message: "Maintenance block created",
      bookingId: data.booking_id,
    };
  } catch (error) {
    console.error("Error creating maintenance block:", error);
    return { success: false, message: "Failed to create maintenance block" };
  }
}

export async function splitBooking(
  bookingId: string,
  splitDate: Date,
): Promise<ActionState> {
  const supabase = await createClient();

  try {
    const { error } = await supabase.rpc("split_booking", {
      p_booking_id: bookingId,
      p_split_date: splitDate.toISOString(),
    });

    if (error) throw error;
    revalidatePath("/admin/bookings");
    return { success: true, message: "Booking split successfully" };
  } catch (error: any) {
    console.error("Error splitting booking:", error);
    return { success: false, message: error.message };
  }
}

export async function reassignBooking(
  bookingId: string,
  newCarId: string,
  newPrice: number,
): Promise<ActionState> {
  const supabase = await createClient();

  try {
    const { error } = await supabase
      .from("bookings")
      .update({
        car_id: newCarId,
        total_price: newPrice, // THE CRUCIAL PRICE UPDATE!
        booking_status: "confirmed", // Since they accepted the proposal
        last_updated_at: new Date().toISOString(),
      })
      .eq("booking_id", bookingId);

    if (error) throw error;

    revalidatePath("/admin/bookings");
    return { success: true, message: "Booking reassigned and price updated" };
  } catch (error: any) {
    console.error("Failed to reassign booking:", error);
    return { success: false, message: error.message };
  }
}

// --- READ: Customer's Personal Bookings ---
export async function getCustomerBookings() {
  const supabase = await createClient();

  // 1. Get the logged-in user
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();
  if (authError || !user) {
    return { success: false, message: "Unauthorized", data: [] };
  }

  // 2. Fetch only their bookings, joining the car and payments data
  const { data, error } = await supabase
    .from("bookings")
    .select(
      `
      *,
      car: cars(brand, model, plate_number, car_images(image_url, is_primary)),
      payments: booking_payments(amount, status)
    `,
    )
    .eq("user_id", user.id)
    .order("created_at", { ascending: false });

  if (error) {
    console.error("Error fetching customer bookings:", error);
    return { success: false, message: error.message, data: [] };
  }

  // 3. Format the data for the UI
  const formattedData = data.map((b: any) => {
    // Extract Primary Image
    if (b.car && b.car.car_images) {
      const primary = b.car.car_images.find((img: any) => img.is_primary);
      b.car.image_url = primary
        ? primary.image_url
        : b.car.car_images[0]?.image_url;
    }

    // Calculate Payments
    const approvedPayments =
      b.payments?.filter((p: any) => p.status === "Approved") || [];
    const pendingPayments =
      b.payments?.filter((p: any) => p.status === "Pending") || [];

    const amountPaid = approvedPayments.reduce(
      (sum: number, p: any) => sum + Number(p.amount),
      0,
    );
    const pendingAmount = pendingPayments.reduce(
      (sum: number, p: any) => sum + Number(p.amount),
      0,
    );

    return {
      id: b.booking_id.split("-")[0].toUpperCase(),
      original_id: b.booking_id,
      car: {
        brand: b.car?.brand,
        model: b.car?.model,
        image: b.car?.image_url || "https://placehold.co/600x400?text=No+Image",
      },
      startDate: new Date(b.start_date),
      endDate: new Date(b.end_date),
      status: b.booking_status,

      // --- NEWLY ADDED PROPERTIES ---
      paymentMethod: b.payment_method || "gcash",
      pickupLocation: b.pickup_location,
      dropoffLocation: b.dropoff_location,
      pickupCoords: b.pickup_coordinates || null,
      dropoffCoords: b.dropoff_coordinates || null,
      // ------------------------------

      totalAmount: Number(b.total_price),
      amountPaid: amountPaid,
      pendingAmount: pendingAmount,
      driver: b.is_with_driver,
    };
  });

  return { success: true, data: formattedData };
}

export async function submitPaymentReceipt(
  bookingId: string,
  amount: number,
  referenceNumber: string,
  receiptUrl: string,
): Promise<ActionState> {
  const supabase = await createClient();

  // Call the atomic RPC
  const { error } = await supabase.rpc("submit_payment_receipt_v1", {
    p_booking_id: bookingId,
    p_amount: amount,
    p_reference_number: referenceNumber || "N/A",
    p_receipt_url: receiptUrl,
  });

  if (error) {
    console.error("RPC Error (Submit Payment):", error);
    return { success: false, message: "Failed to record payment." };
  }

  // Revalidate UI
  revalidatePath("/customer/my-bookings");
  revalidatePath("/admin/bookings");
  return { success: true, message: "Receipt uploaded successfully!" };
}
