import { z } from "zod";

const CoordinateSchema = z.object({
  lat: z.number(),
  lng: z.number(),
});

export const ServiceAreaSchema = z.array(z.array(CoordinateSchema));
export type ServiceArea = z.infer<typeof ServiceAreaSchema>;

// ==========================================
// 1. BOOKING FEES (The numbers)
// ==========================================
export const BookingFeesSchema = z.object({
  driver_rate_per_day: z.coerce.number().min(0, "Must be positive"),
  security_deposit_default: z.coerce.number().min(0),
  custom_pickup_fee: z.coerce.number().min(0),
  custom_dropoff_fee: z.coerce.number().min(0),
  rush_fee: z.coerce.number().default(0),
});

export type BookingFeesSettings = z.infer<typeof BookingFeesSchema>;

// ==========================================
// 2. BUSINESS HUBS (The Map Pins)
// ==========================================
export const HubSchema = z.object({
  id: z.string().optional(), // Generated by frontend if new
  name: z.string().min(1, "Name is required"),
  address: z.string().min(1, "Address is required"),
  lat: z.number(),
  lng: z.number(),
  is_active: z.boolean().default(true),
});

export const BusinessHubsSchema = z.array(HubSchema);

export type BusinessHub = z.infer<typeof HubSchema>;

// ==========================================
// 3. TAX SETTINGS (VAT / Inclusive)
// ==========================================
export const TaxSettingsSchema = z.object({
  enabled: z.boolean(),
  tax_name: z.string().default("VAT"), // e.g. "VAT" or "Sales Tax"
  percentage: z.coerce.number().min(0).max(100),
  is_inclusive: z.boolean().default(true), // True = Price includes tax
  registration_number: z.string().optional(), // TIN or BIR Reg No.
});

export type TaxSettings = z.infer<typeof TaxSettingsSchema>;

// ==========================================
// 4. PAYMENT METHODS (GCash, Bank, etc.)
// ==========================================
const PaymentMethodDetailSchema = z.object({
  enabled: z.boolean(),
  account_name: z.string().optional(),
  account_number: z.string().optional(),
  instructions: z.string().optional(), // "Send screenshot to..."
  qr_code_url: z.string().url().optional().nullable(),
});

export const PaymentMethodsSchema = z
  .object({
    cash: PaymentMethodDetailSchema.optional(),
    gcash: PaymentMethodDetailSchema.optional(),
    bdo: PaymentMethodDetailSchema.optional(),
    bpi: PaymentMethodDetailSchema.optional(),
    maya: PaymentMethodDetailSchema.optional(),
    // Allow other keys if you add them later
  })
  .catchall(PaymentMethodDetailSchema);

export type PaymentMethodSettings = z.infer<typeof PaymentMethodsSchema>;

// ==========================================
// 5. COMPANY PROFILE (For Receipts/Contracts)
// ==========================================
export const CompanyProfileSchema = z.object({
  name: z.string().min(1, "Company Name is required"),
  address: z.string().min(1, "Address is required"),
  contact_number: z.string().min(1, "Contact # is required"),
  email: z.string().email(),
  website: z.string().url().optional().or(z.literal("")), // Valid URL or empty string
  logo_url: z.string().optional().nullable(),
});

export type CompanySettings = z.infer<typeof CompanyProfileSchema>;

// ==========================================
// MASTER SETTINGS UPDATE SCHEMA
// (Used for the Server Action to update any key)
// ==========================================
export const UpdateSettingSchema = z.object({
  key: z.enum([
    "booking_fees",
    "business_hubs",
    "tax_settings",
    "payment_methods",
    "company_profile",
  ]),
  // We use 'unknown' here because we validate the value
  // dynamically inside the action based on the key
  value: z.unknown(),
});

export type UpdateSettingInput = z.infer<typeof UpdateSettingSchema>;
